/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyMenu {}
}

declare global {


  interface HTMLMyMenuElement extends Components.MyMenu, HTMLStencilElement {}
  var HTMLMyMenuElement: {
    prototype: HTMLMyMenuElement;
    new (): HTMLMyMenuElement;
  };
  interface HTMLElementTagNameMap {
    'my-menu': HTMLMyMenuElement;
  }
}

declare namespace LocalJSX {
  interface MyMenu extends JSXBase.HTMLAttributes<HTMLMyMenuElement> {}

  interface IntrinsicElements {
    'my-menu': MyMenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


